<?php $__env->startSection('title','Reports'); ?>
<?php $__env->startSection('page-title','Reports &amp; Analytics'); ?>
<?php $__env->startSection('content'); ?>

<div class="ilap-page-header ilap-flex items-center justify-between ilap-flex-wrap gap-3">
    <div>
        <h1 class="ilap-text-2xl ilap-font-extrabold" style="color:var(--ilap-primary-dark)">
            Reports &amp; Analytics
        </h1>
        <p class="ilap-text-sm text-slate-500 ilap-mt-1">All reports, exports and visual analytics in one place.</p>
    </div>
</div>

<div class="ilap-grid-3 ilap-mb-6">
    <?php $__currentLoopData = [
            ['title'=>'Student Report','icon'=>'🎓','desc'=>'Registered / enrolled / completed student counts by campus','route'=>'reports.students','count'=>$campuses?->count() ?? $campuses->count()],
            ['title'=>'Payment Report','icon'=>'💰','desc'=>'Revenue, pending payments, and instalment overview','route'=>'reports.payments','count'=>$payments?->count() ?? 0],
            ['title'=>'Ticket Report','icon'=>'🎫','desc'=>'Open, in-progress and resolved tickets — all campuses','route'=>'reports.tickets','count'=>$tickets?->count() ?? 0],
            ['title'=>'Campus Report','icon'=>'🏫','desc'=>'Per-campus enrollment, finance and activity summary','route'=>'reports.campus','count'=>$campuses?->count() ?? 0],
            ['title'=>'Lead Status Report','icon'=>'📋','desc'=>'New → converted pipeline — source breakdown','route'=>'reports.lead-status','count'=>\App\Models\Lead::count()],
            ['title'=>'Handler Performance','icon'=>'📊','desc'=>'Individual handler lead and student performance','route'=>'reports.handler-performance','count'=>\App\Models\Handler::active()->count()],
        ]; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $report): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
    <a href="<?php echo e(route($report['route'])); ?>"
       class="ilap-card hover:shadow-lg transition-shadow group">
        <div class="ilap-p-5">
            <div class="ilap-flex items-center justify-between mb-4">
                <span class="ilap-text-3xl"><?php echo e($report['icon']); ?></span>
                <span class="ilap-badge" style="background:var(--ilap-primary-light);color:var(--ilap-primary)">
                    <?php echo e($report['count']); ?> items
                </span>
            </div>
            <h3 class="ilap-font-bold text-slate-800"><?php echo e($report['title']); ?></h3>
            <p class="ilap-text-xs text-slate-500 ilap-mt-1"><?php echo e($report['desc']); ?></p>
            <p class="ilap-text-xs font-bold mt-2" style="color:var(--ilap-primary)">Open report →</p>
        </div>
    </a>
    <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
</div>

<div class="ilap-card">
    <div class="ilap-card-header">
        <h3 class="ilap-m-0 ilap-font-bold text-slate-800">Recent Reports</h3>
    </div>
    <div class="ilap-table__wrap">
        <table class="ilap-table">
            <thead>
                <tr>
                    <th>Report Title</th>
                    <th>Type</th>
                    <th>Generated By</th>
                    <th>Generated At</th>
                    <th>Format</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
            <?php $__empty_1 = true; $__currentLoopData = ($reports ?? collect()); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $log): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
            <tr>
                <td class="ilap-font-semibold text-slate-700"><?php echo e($log->title); ?></td>
                <td><span class="ilap-badge ilap-badge--blue"><?php echo e(ucfirst($log->type)); ?></span></td>
                <td class="ilap-text-sm"><?php echo e($log->generator?->name ?? '—'); ?></td>
                <td class="ilap-text-xs text-slate-500"><?php echo e($log->generated_at?->diffForHumans() ?? '—'); ?></td>
                <td><span class="ilap-badge ilap-badge--gray"><?php echo e(strtoupper($log->format ?? 'PDF')); ?></span></td>
                <td><a href="#" class="ilap-text-sm font-bold hover:underline" style="color:var(--ilap-primary)">Download</a></td>
            </tr>
            <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?>
            <tr>
                <td colspan="6" class="ilap-text-center ilap-py-8 text-slate-400">
                    No reports generated yet.
                </td>
            </tr>
            <?php endif; ?>
            </tbody>
        </table>
    </div>
</div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH /var/www/html/Projects/l/resources/views/reports/index.blade.php ENDPATH**/ ?>