{{-- resources/views/reports/index.blade.php --}}
@extends('layouts.app')

@section('title','Reports')
@section('page-title','Reports &amp; Analytics')
@section('content')

<div class="ilap-page-header ilap-flex items-center justify-between ilap-flex-wrap gap-3">
    <div>
        <h1 class="ilap-text-2xl ilap-font-extrabold" style="color:var(--ilap-primary-dark)">
            Reports &amp; Analytics
        </h1>
        <p class="ilap-text-sm text-slate-500 ilap-mt-1">All reports, exports and visual analytics in one place.</p>
    </div>
</div>

<div class="ilap-grid-3 ilap-mb-6">
    @foreach(
        [
            ['title'=>'Student Report','icon'=>'🎓','desc'=>'Registered / enrolled / completed student counts by campus','route'=>'reports.students','count'=>$campuses?->count() ?? $campuses->count()],
            ['title'=>'Payment Report','icon'=>'💰','desc'=>'Revenue, pending payments, and instalment overview','route'=>'reports.payments','count'=>$payments?->count() ?? 0],
            ['title'=>'Ticket Report','icon'=>'🎫','desc'=>'Open, in-progress and resolved tickets — all campuses','route'=>'reports.tickets','count'=>$tickets?->count() ?? 0],
            ['title'=>'Campus Report','icon'=>'🏫','desc'=>'Per-campus enrollment, finance and activity summary','route'=>'reports.campus','count'=>$campuses?->count() ?? 0],
            ['title'=>'Lead Status Report','icon'=>'📋','desc'=>'New → converted pipeline — source breakdown','route'=>'reports.lead-status','count'=>\App\Models\Lead::count()],
            ['title'=>'Handler Performance','icon'=>'📊','desc'=>'Individual handler lead and student performance','route'=>'reports.handler-performance','count'=>\App\Models\Handler::active()->count()],
        ] as $report)
    <a href="{{ route($report['route']) }}"
       class="ilap-card hover:shadow-lg transition-shadow group">
        <div class="ilap-p-5">
            <div class="ilap-flex items-center justify-between mb-4">
                <span class="ilap-text-3xl">{{ $report['icon'] }}</span>
                <span class="ilap-badge" style="background:var(--ilap-primary-light);color:var(--ilap-primary)">
                    {{ $report['count'] }} items
                </span>
            </div>
            <h3 class="ilap-font-bold text-slate-800">{{ $report['title'] }}</h3>
            <p class="ilap-text-xs text-slate-500 ilap-mt-1">{{ $report['desc'] }}</p>
            <p class="ilap-text-xs font-bold mt-2" style="color:var(--ilap-primary)">Open report →</p>
        </div>
    </a>
    @endforeach
</div>

<div class="ilap-card">
    <div class="ilap-card-header">
        <h3 class="ilap-m-0 ilap-font-bold text-slate-800">Recent Reports</h3>
    </div>
    <div class="ilap-table__wrap">
        <table class="ilap-table">
            <thead>
                <tr>
                    <th>Report Title</th>
                    <th>Type</th>
                    <th>Generated By</th>
                    <th>Generated At</th>
                    <th>Format</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
            @forelse(($reports ?? collect()) as $log)
            <tr>
                <td class="ilap-font-semibold text-slate-700">{{ $log->title }}</td>
                <td><span class="ilap-badge ilap-badge--blue">{{ ucfirst($log->type) }}</span></td>
                <td class="ilap-text-sm">{{ $log->generator?->name ?? '—' }}</td>
                <td class="ilap-text-xs text-slate-500">{{ $log->generated_at?->diffForHumans() ?? '—' }}</td>
                <td><span class="ilap-badge ilap-badge--gray">{{ strtoupper($log->format ?? 'PDF') }}</span></td>
                <td><a href="#" class="ilap-text-sm font-bold hover:underline" style="color:var(--ilap-primary)">Download</a></td>
            </tr>
            @empty
            <tr>
                <td colspan="6" class="ilap-text-center ilap-py-8 text-slate-400">
                    No reports generated yet.
                </td>
            </tr>
            @endforelse
            </tbody>
        </table>
    </div>
</div>
@endsection
